# Generated by Django 3.2 on 2022-05-16 17:32

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanModel',
            fields=[
                ('plan_type', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], default='free', max_length=4)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('max_knowledge_base', models.IntegerField(blank=True, default='1')),
                ('max_megabyte', models.FloatField(blank=True, default='5', max_length=30)),
                ('max_users', models.IntegerField(blank=True, default='1')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='corev1.planmodel')),
            ],
        ),
    ]
