# Generated by Django 3.2 on 2022-04-29 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corev1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planmodel',
            name='organization',
        ),
        migrations.AddField(
            model_name='organizationmodel',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='corev1.planmodel'),
        ),
    ]
