# Generated by Django 3.2 on 2022-06-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corev1', '0002_foldermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foldermodel',
            name='deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foldermodel',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
