# Generated by Django 3.2 on 2022-06-02 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corev1', '0003_auto_20220602_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foldermodel',
            name='user_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.usermodel'),
        ),
    ]
