# Generated by Django 4.0.3 on 2022-04-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corev1', '0003_alter_usermodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(max_length=30, unique=True),
        ),
    ]
