# Generated by Django 4.0.3 on 2022-04-02 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corev1', '0004_alter_usermodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmodel',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
