# Generated by Django 4.0.3 on 2022-04-15 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corev1', '0010_alter_organizationmodel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmodel',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corev1.usermodel'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='organization',
            field=models.CharField(max_length=30),
        ),
    ]
