# Generated by Django 4.0.3 on 2022-04-15 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corev1', '0011_alter_organizationmodel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmodel',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='corev1.usermodel'),
        ),
    ]
