# Generated by Django 4.0.3 on 2022-04-15 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corev1', '0012_alter_organizationmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmodel',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corev1.organizationmodel'),
        ),
    ]
