# Generated by Django 4.0.3 on 2022-04-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corev1', '0013_alter_organizationmodel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='organization',
            field=models.CharField(max_length=30),
        ),
    ]
