# Generated by Django 4.0.3 on 2022-04-15 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corev1', '0015_alter_usermodel_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='organization',
            field=models.CharField(max_length=30),
        ),
    ]
